<a href="https://colab.research.google.com/github/itachi289/pds/blob/main/Assignment_2_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Use this data to perform the following:

a. Look for the missing values in all the columns and either impute them (replace with mean,median, or mode) or drop them. Justify your action for this task.

In [18]:
import pandas as pd

In [19]:
#Load the dataset
from google.colab import files
uploaded = files.upload()
data = pd.read_csv('train.csv')

Saving train.csv to train (1).csv

In [20]:
# Check for missing values in all columns
missing_values_before = data.isnull().sum()

# Display the missing values count for each column
print("Missing Values Before Imputation:")
print(missing_values_before)

Missing Values Before Imputation:
Unnamed: 0              0
Name                    0
Location                0
Year                    0
Kilometers_Driven       0
Fuel_Type               0
Transmission            0
Owner_Type              0
Mileage                 2
Engine                 36
Power                  36
Seats                  38
New_Price            5032
Price                   0
dtype: int64

In [21]:
# Impute numerical columns with the median (for columns with skewed distribution or outliers)
numerical_columns = data.select_dtypes(include=['float64', 'int64']).columns
for column in numerical_columns:
    data[column] = data[column].fillna(data[column].median())

# Impute categorical columns with the mode (most frequent value)
categorical_columns = data.select_dtypes(include=['object']).columns
for column in categorical_columns:
    data[column] = data[column].fillna(data[column].mode()[0])

# Verify if any missing values remain
missing_values_after = data.isnull().sum()

# Display the results
print("\nMissing Values After Imputation:")
print(missing_values_after)

Missing Values After Imputation:
Unnamed: 0           0
Name                 0
Location             0
Year                 0
Kilometers_Driven    0
Fuel_Type            0
Transmission         0
Owner_Type           0
Mileage              0
Engine               0
Power                0
Seats                0
New_Price            0
Price                0
dtype: int64

New_Price: Dropped due to a large number of missing values.

B. Remove the units from some of the attributes and only keep the numerical values for example remove kmpl from “Mileage”, CC from “Engine”, bhp from “Power”, and lakh from

In [22]:
# Remove 'kmpl' from 'Mileage' and convert to numeric
data['Mileage'] = data['Mileage'].replace(r' kmpl', '', regex=True)
data['Mileage'] = data['Mileage'].replace(r' km/kg', '', regex=True)  # in case of km/kg
data['Mileage'] = pd.to_numeric(data['Mileage'], errors='coerce')

In [23]:
# Remove 'CC' from 'Engine' and convert to numeric (only the first part before 'CC')
data['Engine'] = data['Engine'].replace(r' CC', '', regex=True)
data['Engine'] = data['Engine'].replace(r'(\d+)', r'\1', regex=True)  # Keep numeric part only
data['Engine'] = pd.to_numeric(data['Engine'], errors='coerce')

In [24]:
# Remove 'bhp' from 'Power' and convert to numeric
data['Power'] = data['Power'].replace(r' bhp', '', regex=True)
data['Power'] = pd.to_numeric(data['Power'], errors='coerce')

In [25]:
# Remove 'Lakh' from 'New_Price' and convert to numeric (replace ' Lakh' with nothing)
data['New_Price'] = data['New_Price'].replace(r' Lakh', '', regex=True)
data['New_Price'] = data['New_Price'].replace(r',', '', regex=True)  # In case of commas in large numbers
data['New_Price'] = pd.to_numeric(data['New_Price'], errors='coerce')


# Display the cleaned data
data.head()

,Unnamed: 0,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price
0,1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,Diesel,Manual,First,19.67,1582,126.20,5.0,4.78,12.50
1,2,Honda Jazz V,Chennai,2011,46000,Petrol,Manual,First,13.00,1199,88.70,5.0,8.61,4.50
2,3,Maruti Ertiga VDI,Chennai,2012,87000,Diesel,Manual,First,20.77,1248,88.76,7.0,4.78,6.00
3,4,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,Diesel,Automatic,Second,15.20,1968,140.80,5.0,4.78,17.74
4,6,Nissan Micra Diesel XV,Jaipur,2013,86999,Diesel,Manual,First,23.08,1461,63.10,5.0,4.78,3.50

C)  Change the categorical variables (“Fuel_Type” and “Transmission”) into numerical one hot
encoded value.

In [26]:

# One-hot encode 'Fuel_Type' and 'Transmission' columns
data=pd.get_dummies(data,columns=['Fuel_Type', 'Transmission'], drop_first=True)

# Display the first few rows of the updated data
data.head()

,Unnamed: 0,Name,Location,Year,Kilometers_Driven,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price,Fuel_Type_Electric,Fuel_Type_Petrol,Transmission_Manual
0,1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,First,19.67,1582,126.20,5.0,4.78,12.50,False,False,True
1,2,Honda Jazz V,Chennai,2011,46000,First,13.00,1199,88.70,5.0,8.61,4.50,False,True,True
2,3,Maruti Ertiga VDI,Chennai,2012,87000,First,20.77,1248,88.76,7.0,4.78,6.00,False,False,True
3,4,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,Second,15.20,1968,140.80,5.0,4.78,17.74,False,False,False
4,6,Nissan Micra Diesel XV,Jaipur,2013,86999,First,23.08,1461,63.10,5.0,4.78,3.50,False,False,True

d) Create one more feature and add this column to the dataset (you can use mutate function in
R for this). For example, you can calculate the current age of the car by subtracting “Year” value
from the current year.

In [27]:
# Import the current year
from datetime import datetime

In [28]:
# Get the current year
current_year = datetime.now().year

In [29]:
# Calculate the car's age by subtracting the "Year" from the current year
data['Car_Age'] = current_year - data['Year']

In [30]:
# Display the updated data with the new 'Car_Age' feature
data.head()

,Unnamed: 0,Name,Location,Year,Kilometers_Driven,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price,Fuel_Type_Electric,Fuel_Type_Petrol,Transmission_Manual,Car_Age
0,1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,First,19.67,1582,126.20,5.0,4.78,12.50,False,False,True,10
1,2,Honda Jazz V,Chennai,2011,46000,First,13.00,1199,88.70,5.0,8.61,4.50,False,True,True,14
2,3,Maruti Ertiga VDI,Chennai,2012,87000,First,20.77,1248,88.76,7.0,4.78,6.00,False,False,True,13
3,4,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,Second,15.20,1968,140.80,5.0,4.78,17.74,False,False,False,12
4,6,Nissan Micra Diesel XV,Jaipur,2013,86999,First,23.08,1461,63.10,5.0,4.78,3.50,False,False,True,12

e) Perform select, filter, rename, mutate, arrange and summarize with group by operations (or
their equivalent operations in python) on this dataset.

In [31]:
# Select specific columns
selected_data = data[['Name', 'Price', 'Mileage', 'Car_Age']]

# Display the selected data
selected_data.head()

                               Name  Price  Mileage  Car_Age
0  Hyundai Creta 1.6 CRDi SX Option  12.50    19.67       10
1                      Honda Jazz V   4.50    13.00       14
2                 Maruti Ertiga VDI   6.00    20.77       13
3   Audi A4 New 2.0 TDI Multitronic  17.74    15.20       12
4            Nissan Micra Diesel XV   3.50    23.08       12

In [32]:
# Filter rows where car price is greater than 8
filtered_data = data[data['Price'] > 8]

# Display the filtered data
filtered_data.head()

,Unnamed: 0,Name,Location,Year,Kilometers_Driven,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price,Fuel_Type_Electric,Fuel_Type_Petrol,Transmission_Manual,Car_Age
0,1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,First,19.67,1582,126.20,5.0,4.78,12.50,False,False,True,10
3,4,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,Second,15.20,1968,140.80,5.0,4.78,17.74,False,False,False,12
5,7,Toyota Innova Crysta 2.8 GX AT 8S,Mumbai,2016,36000,First,11.36,2755,171.50,8.0,21.00,17.50,False,False,False,9
8,10,Maruti Ciaz Zeta,Kochi,2018,25692,First,21.56,1462,103.25,5.0,10.65,9.95,False,True,True,7
11,13,Land Rover Range Rover 2.2L Pure,Delhi,2014,72000,First,12.70,2179,187.70,5.0,4.78,27.00,False,False,False,11

In [33]:
# Rename columns (equivalent to rename in R)
data.rename(columns={'Price':'Car_Price', 'Mileage':'Fuel_Efficiency'}, inplace=True)

# Display the renamed data
data.head()

,Unnamed: 0,Name,Location,Year,Kilometers_Driven,Owner_Type,Fuel_Efficiency,Engine,Power,Seats,New_Price,Car_Price,Fuel_Type_Electric,Fuel_Type_Petrol,Transmission_Manual,Car_Age
0,1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,First,19.67,1582,126.20,5.0,4.78,12.50,False,False,True,10
1,2,Honda Jazz V,Chennai,2011,46000,First,13.00,1199,88.70,5.0,8.61,4.50,False,True,True,14
2,3,Maruti Ertiga VDI,Chennai,2012,87000,First,20.77,1248,88.76,7.0,4.78,6.00,False,False,True,13
3,4,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,Second,15.20,1968,140.80,5.0,4.78,17.74,False,False,False,12
4,6,Nissan Micra Diesel XV,Jaipur,2013,86999,First,23.08,1461,63.10,5.0,4.78,3.50,False,False,True,12

In [34]:
# Function to convert km/l to miles/gallon
def kmpl_to_mpg(kmpl):
    return kmpl * 0.621371 * 0.264172 if isinstance(kmpl, (int, float)) else None

# Add new column with the conversion
data['Mileage_in_miles'] = data['Fuel_Efficiency'].apply(kmpl_to_mpg)

# Display the updated data
data.head()

,Unnamed: 0,Name,Location,Year,Kilometers_Driven,Owner_Type,Fuel_Efficiency,Engine,Power,Seats,New_Price,Car_Price,Fuel_Type_Electric,Fuel_Type_Petrol,Transmission_Manual,Car_Age,Mileage_in_miles
0,1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,First,19.67,1582,126.20,5.0,4.78,12.50,False,False,True,10,3.228807
1,2,Honda Jazz V,Chennai,2011,46000,First,13.00,1199,88.70,5.0,8.61,4.50,False,True,True,14,2.133935
2,3,Maruti Ertiga VDI,Chennai,2012,87000,First,20.77,1248,88.76,7.0,4.78,6.00,False,False,True,13,3.409371
3,4,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,Second,15.20,1968,140.80,5.0,4.78,17.74,False,False,False,12,2.495062
4,6,Nissan Micra Diesel XV,Jaipur,2013,86999,First,23.08,1461,63.10,5.0,4.78,3.50,False,False,True,12,3.788555

In [35]:
# Arrange: Sort data by 'Car_Age' in ascending order and 'Car_Price' in descending order
arranged_data = data.sort_values(by=['Car_Age', 'Car_Price'], ascending=[True, False])

# Display the arranged data
arranged_data.head()

,Unnamed: 0,Name,Location,Year,Kilometers_Driven,Owner_Type,Fuel_Efficiency,Engine,Power,Seats,New_Price,Car_Price,Fuel_Type_Electric,Fuel_Type_Petrol,Transmission_Manual,Car_Age,Mileage_in_miles
1457,1505,Land Rover Range Rover Sport SE,Kochi,2019,26013,First,12.65,2993,255.00,5.0,NaN,97.07,False,False,False,6,2.076483
2035,2095,Mercedes-Benz SLC 43 AMG,Coimbatore,2019,2526,First,19.00,2996,362.07,2.0,NaN,83.96,False,True,False,6,3.118828
2251,2319,Mercedes-Benz E-Class E 350 d,Coimbatore,2019,9312,First,18.00,2987,258.00,5.0,92.50,78.80,False,False,False,6,2.954679
1532,1583,Audi Q7 45 TDI Quattro Premium Plus,Kochi,2019,6773,First,14.75,2967,245.00,7.0,91.38,72.94,False,False,False,6,2.421195
4921,5067,Land Rover Discovery Sport SD4 HSE Luxury 7S,Coimbatore,2019,17201,First,12.51,2179,187.70,7.0,4.78,58.91,False,False,False,6,2.053502

In [36]:
# Group by 'Owner_Type' and calculate count, mean, and sum for 'Kilometers_Driven' and 'Seats'
summary_data = data.groupby('Owner_Type').agg({
    'Kilometers_Driven': ['count', 'mean', 'sum'],   # Count, mean, and sum of 'Kilometers_Driven'
    'Seats': ['mean', 'sum']                         # Mean and sum of 'Seats'
}).reset_index()

# Display the summarized data
print(summary_data.head())

       Owner_Type Kilometers_Driven                               Seats  \
                              count           mean        sum      mean
0           First              4811   55193.302224  265534977  5.283309
1  Fourth & Above                 8  124354.125000     994833  5.875000
2          Second               925   71175.587027   65837418  5.277838
3           Third               103   88901.252427    9156829  5.359223


       sum
0  25418.0
1     47.0
2   4882.0
3    552.0